Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2023-10, with the labels that each got.

#565 [Hotfix] Fix electron, easydl, update mm to 11.1.0
  package.json
  public/extensions/MetaMask_v10.22.2/_locales/de/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/el/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/en/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/es/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/es_419/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/fr/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/hi/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/id/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/ja/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/ko/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/pt/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/pt_BR/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/ru/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/tl/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/tr/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/vi/messages.json
  public/extensions/MetaMask_v10.22.2/_locales/zh_CN/messages.json
  public/extensions/MetaMask_v10.22.2/background-2.js
  public/extensions/MetaMask_v10.22.2/common-2.js
  public/extensions/MetaMask_v10.22.2/images/contract/ndc.png
  public/extensions/MetaMask_v10.22.2/index-rtl.css
  public/extensions/MetaMask_v10.22.2/index.css
  public/extensions/MetaMask_v10.22.2/lockdown-install.js
  public/extensions/MetaMask_v10.22.2/manifest.json
  public/extensions/MetaMask_v10.22.2/runtime-cjs.js
  public/extensions/MetaMask_v10.22.2/runtime-lavamoat.js
  public/extensions/MetaMask_v10.22.2/sentry-install.js
  public/extensions/MetaMask_v10.22.2/ui-10.js
  public/extensions/MetaMask_v10.22.2/ui-11.js
  public/extensions/MetaMask_v10.22.2/ui-12.js
  public/extensions/MetaMask_v10.22.2/ui-4.js
  public/extensions/MetaMask_v10.22.2/ui-5.js
  public/extensions/MetaMask_v10.22.2/ui-6.js
  public/extensions/MetaMask_v10.22.2/ui-7.js
  public/extensions/MetaMask_v10.22.2/ui-8.js
  public/extensions/MetaMask_v10.22.2/ui-9.js
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/utils.ts
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#567 [FIX] Linux Menu Icon for AUR, DEB and RPM
  package.json
  public/app_icon.icns
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#526 [CI] Automate Snaps and AUR releases
  .github/workflows/release_aur.yml
  package.json
Labels: PR: Ready-For-Review

#574 [CI] Add mac arm64 runner
  .github/workflows/build-mac-arm64.yml
  .github/workflows/build.yml
  .github/workflows/release_macOS.yml
  package.json
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#571 [UI] Fix grid spacing, text overflow
  src/frontend/screens/Game/GamePage/index.scss
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#557 [UX] Check access code on install modal
  public/locales/en/translation.json
  src/backend/api/library.ts
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/TextInputField/index.css
  src/frontend/components/UI/TextInputField/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.module.scss
  src/frontend/screens/Library/components/InstallModal/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#532 [Fix] Library Filtering
  package.json
  src/backend/storeManagers/legendary/library.ts
  src/common/types.ts
  src/frontend/components/UI/ErrorComponent/index.tsx
  src/frontend/components/UI/SearchBar/index.tsx
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/frontend/components/UI/StoreFilter/index.tsx
  src/frontend/components/UI/ThemeSelector/index.tsx
  src/frontend/components/UI/TopNavBar/index.tsx
  src/frontend/helpers/index.ts
  src/frontend/helpers/library.ts
  src/frontend/hooks/constants.ts
  src/frontend/hooks/hasStatus.ts
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameSubMenu/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/GamesList/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
  src/frontend/screens/Library/components/LibraryTopBar/index.tsx
  src/frontend/screens/Library/components/RecentlyPlayed/index.tsx
  src/frontend/screens/Library/index.tsx
  src/frontend/screens/Login/components/SIDLogin/index.tsx
  src/frontend/screens/Login/index.tsx
  src/frontend/screens/Settings/components/EgsSettings.tsx
  src/frontend/screens/Settings/components/LibraryTopSection.tsx
  src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
  src/frontend/screens/WebView/index.tsx
  src/frontend/screens/WineManager/index.tsx
  src/frontend/state/ContextProvider.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/state/__tests__/libraryState.test.ts
  src/frontend/state/libraryState.ts
  src/frontend/state/storeAuthState.ts
  src/frontend/store/index.tsx
  src/frontend/types.ts
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#583 [Tech] Refactor to use electron downloader
  e2e/__specs__/hpStoreApi.spec.ts
  package.json
  src/backend/api/downloadmanager.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/downloadmanager/ipc_handler.ts
  src/backend/storeManagers/gog/games.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/legendary/games.ts
  src/backend/storeManagers/nile/games.ts
  src/backend/storeManagers/sideload/games.ts
  src/backend/utils.ts
  src/backend/utils/downloadFile/download_file.ts
  src/backend/utils/downloadFile/types.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types/game_manager.ts
  src/frontend/components/UI/DownloadToastManager/index.tsx
  src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/state/DMQueueState.ts
  yarn.lock
Labels: Priority: 1 - Highest, PR: Ready-For-Review, PR: Ready-For-Test

#609 [Fix] Launch of sideloaded browser games
  src/backend/storeManagers/storeManagerCommon/games.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#611 [FIX] Sideloaded apps not showing after restart
  src/frontend/state/libraryState.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test
