Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2023-08, with the labels that each got.

#437 [Fix] Asar extraction
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: ready-for-review, PR: ready-for-test

#434 [Feature] Access codes
  src/backend/constants.ts
  src/backend/downloadmanager/utils.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/common/types.ts
  src/frontend/helpers/library.ts
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.tsx
Labels: PR: ready-for-review, PR: ready-for-test

#438 [Fix] rm encodeUri of already formed url
  src/backend/utils.ts
Labels: PR: ready-for-review, PR: ready-for-test

#411 [CI/CD] Fix linux and mac builds and releases. Automate flathub releases
  .github/workflows/build.yml
  .github/workflows/codecheck.yml
  .github/workflows/flatpak-build.yml
  .github/workflows/lint.yml
  .github/workflows/release_flathub.yml
  .github/workflows/submodules-are-merged.yml
  .github/workflows/test-e2e-dev.yml
  .github/workflows/test-e2e-packaged.yml
  .github/workflows/test.yml
  .gitignore
  flathub/update-flathub.ts
  package.json
  yarn.lock
Labels: PR: ready-for-review

#416 [Tech] Add LavaMoat allow scripts
  .github/workflows/build.yml
  .github/workflows/codecheck.yml
  .github/workflows/flatpak-build.yml
  .github/workflows/lint.yml
  .github/workflows/release_flathub.yml
  .github/workflows/release_linux.yml
  .github/workflows/release_macOS.yml
  .github/workflows/test-e2e-dev.yml
  .github/workflows/test-e2e-packaged.yml
  .github/workflows/test.yml
  .gitignore
  .yarnrc
  .yarnrc.yml
  package.json
  yarn.lock
Labels: PR: ready-for-review, PR: ready-for-test

#430 [TECH] Add support for Epic DLCs and more
  public/locales/en/gamepage.json
  public/locales/en/translation.json
  src/backend/api/downloadmanager.ts
  src/backend/config.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/launcher.ts
  src/backend/main.ts
  src/backend/shortcuts/shortcuts/shortcuts.ts
  src/backend/storeManagers/gog/games.ts
  src/backend/storeManagers/gog/library.ts
  src/backend/storeManagers/legendary/games.ts
  src/backend/storeManagers/legendary/library.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/common/types/gog.ts
  src/common/types/legendary.ts
  src/frontend/components/UI/DLCList/DLC/index.scss
  src/frontend/components/UI/DLCList/DLC/index.tsx
  src/frontend/components/UI/DLCList/index.scss
  src/frontend/components/UI/DLCList/index.tsx
  src/frontend/components/UI/UninstallModal/index.tsx
  src/frontend/helpers/library.ts
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
  src/frontend/screens/Game/GamePage/index.scss
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameSubMenu/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/DLCDownloadListing.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.css
Labels: PR: ready-for-review, PR: ready-for-test

#453 [Fix] Browser HP game install
  public/locales/en/gamepage.json
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/common/types.ts
  src/frontend/components/UI/ChannelNameSelection/index.tsx
  src/frontend/components/UI/PlatformSelection/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.tsx
  src/frontend/screens/WebView/index.tsx
Labels: PR: ready-for-review, PR: ready-for-test

#486 [Metrics] Fix game install success and fail events
  src/backend/downloadmanager/utils.ts
Labels: PR: ready-for-review

#485 [CICD] Fix e2e tests
  .github/workflows/test-e2e-dev.yml
  .github/workflows/test-e2e-packaged.yml
  e2e/__specs__/api.spec.ts
  e2e/__specs__/common-setup.ts
  e2e/__specs__/hpStoreApi.spec.ts
  e2e/entrypoint.sh
  package.json
  yarn.lock
Labels: PR: ready-for-review, ci/cd
