Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2023-06, with the labels that each got.

#353 [FIX] macOS application icon
  public/app_icon.icns
Labels: PR: ready-for-review, PR: ready-for-test

#345 [Feature] Browser game close through overlay
  package.json
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/frontend/ViewManager.tsx
  src/frontend/browserGame/BrowserExtensionManager/index.module.scss
  src/frontend/browserGame/BrowserExtensionManager/index.tsx
  src/frontend/browserGame/index.tsx
  yarn.lock
Labels: Priority: 3 - Medium, PR: ready-for-review, PR: ready-for-test

#369 [Fix] Uninstall games list layout shift
  src/frontend/components/UI/Dialog/components/Dialog.tsx
  src/frontend/components/UI/Dialog/index.css
Labels: PR: ready-for-review, PR: ready-for-test

#382 [UI] Change X icon to "Exit Game" in browser game overlay
  public/locales/en/translation.json
  src/frontend/browserGame/BrowserExtensionManager/index.tsx
Labels: PR: ready-for-review, PR: ready-for-test

#380 [Feature] Platform Filters
  src/backend/storeManagers/gog/library.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/backend/storeManagers/hyperplay/utils.ts
  src/backend/storeManagers/legendary/library.ts
  src/common/types.ts
  src/frontend/components/UI/PlatformFilter/index.css
  src/frontend/components/UI/PlatformFilter/index.tsx
  src/frontend/screens/Library/index.tsx
  src/frontend/state/ContextProvider.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/types.ts
Labels: Priority: 2 - High, PR: ready-for-review, PR: ready-for-test

#383 [FIX] Platform selection on Add Game screen
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/Warning/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.tsx
Labels: PR: ready-for-review, PR: ready-for-test

#385 [Fix] Launching of native linux games
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: ready-for-review, PR: ready-for-test

#388 [Metrics] Add sentry crash reporting
  package.json
  src/backend/main.ts
  src/common/constants.ts
  src/frontend/index.tsx
  yarn.lock
Labels: PR: ready-for-review, PR: ready-for-test
