Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2023-11, with the labels that each got.

#621 [FIX] Focus Window if the Game Update dialog shows
  public/locales/en/gamepage.json
  src/backend/api/misc.ts
  src/backend/main.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/helpers/library.ts
  src/frontend/state/GlobalState.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#620 [FIX] Game Launch/Close Events
  src/backend/downloadmanager/utils.ts
  src/backend/launcher.ts
  src/backend/main.ts
  src/backend/metrics/metrics.ts
  src/backend/metrics/types.ts
  src/backend/storeManagers/gog/games.ts
  src/backend/storeManagers/gog/library.ts
  src/backend/storeManagers/legendary/games.ts
  src/backend/storeManagers/legendary/library.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/backend/utils.ts
Labels: PR: Ready-For-Review

#624 [Metrics] Add more Download Status Change Events
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/metrics/types.ts
  src/frontend/components/UI/DownloadToastManager/index.tsx
  src/frontend/components/UI/StopInstallationModal/index.tsx
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: PR: Ready-For-Review

#615 [UX] Show Update button instead of Play for game with updates
  public/locales/en/gamepage.json
  src/backend/config.ts
  src/frontend/screens/Game/GamePage/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#622 [Fix] Game Update issues
  src/backend/api/downloadmanager.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/common/types.ts
  src/frontend/helpers/library.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test, Severity: 1 - High

#618 [UX] Improve Download Toast, Disk Space Calculation for Uncompressed & Relaunch Download Toast Issue
  .gitignore
  e2e/__specs__/common-setup.ts
  e2e/__specs__/hpStoreApi.spec.ts
  package.json
  public/locales/en/gamepage.json
  public/locales/en/translation.json
  src/backend/__mocks__/@sentry/electron.ts
  src/backend/__mocks__/谷���新道ひばりヶ�.zip
  src/backend/__tests__/utils.test.ts
  src/backend/api/downloadmanager.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/downloadmanager/ipc_handler.ts
  src/backend/services/ExtractZipService.ts
  src/backend/services/__tests__/ExtractZipService.test.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/utils.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/DownloadToastManager/index.tsx
  src/frontend/components/UI/StopInstallationModal/index.tsx
  src/frontend/hooks/constants.ts
  src/frontend/hooks/hasStatus.ts
  src/frontend/hooks/useEstimatedUncompressedSize.ts
  src/frontend/hooks/useGetDownloadStatusText.ts
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
  src/frontend/screens/DownloadManager/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/constants.ts
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/constants.ts
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#646 [FIX] [CI/CD] Windows update sha512 case error #645
  .github/workflows/release_windows.yml
Labels: PR: Ready-For-Review

#650 [Fix] Portfolio page for non mm extension wallets
  src/frontend/components/UI/AccountDropdown/index.tsx
  src/frontend/screens/MetaMaskPortfolio/index.tsx
Labels: PR: Ready-For-Review

#634 [FIX] MM Dropdown bug
  public/locales/en/translation.json
  src/frontend/components/UI/AccountDropdown/index.tsx
  src/frontend/screens/MetaMaskPortfolio/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test
