Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2023-07, with the labels that each got.

#393 [Fix] Linux missing app icon
  package.json
Labels: PR: ready-for-review, PR: ready-for-test

#400 [Metrics] Opt In Sentry crash reports
  src/backend/main.ts
  src/backend/metrics/metrics.ts
  src/frontend/SentryHandler/index.tsx
  src/frontend/index.tsx
Labels: Priority: 3 - Medium, PR: ready-for-review, PR: ready-for-test

#401 [Feat] Browser game fullscreen hotkey
  src/backend/main_window.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/frontend/OverlayManager/index.tsx
Labels: Priority: 3 - Medium, PR: ready-for-review, PR: ready-for-test

#257 [Feat] Add support for channels
  package.json
  public/locales/en/gamepage.json
  public/locales/en/translation.json
  src/backend/api/helpers.ts
  src/backend/api/library.ts
  src/backend/constants.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/downloadmanager/utils.ts
  src/backend/hyperplay_store_preload.ts
  src/backend/main.ts
  src/backend/protocol.ts
  src/backend/storeManagers/hyperplay/__tests__/utils.test.ts
  src/backend/storeManagers/hyperplay/electronStore.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/hyperplay/legacy_listings.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/backend/storeManagers/hyperplay/utils.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/common/types/electron_store.ts
  src/common/types/game_manager.ts
  src/frontend/components/UI/ToggleSwitch/index.css
  src/frontend/helpers/electronStores.ts
  src/frontend/helpers/index.ts
  src/frontend/helpers/library.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.tsx
  src/frontend/screens/Library/constants.ts
  src/frontend/state/GlobalState.tsx
  yarn.lock
Labels: type: enhancement, Priority: 2 - High, PR: ready-for-review, PR: ready-for-test

#417 [Fix] Sentry init after ready
  src/backend/main.ts
Labels: PR: ready-for-review, PR: ready-for-test
