Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2023-09, with the labels that each got.

#502 [Fix] Browser Game Keyboard Input
  src/backend/storeManagers/storeManagerCommon/games.ts
Labels: PR: ready-for-review, PR: ready-for-test

#501 [Fix] Main access codes
  src/frontend/components/UI/ChannelNameSelection/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.tsx
Labels: PR: ready-for-review, PR: ready-for-test

#503 [Fix] Games with spaces in version name are always updateable
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/backend/storeManagers/hyperplay/utils.ts
  yarn.lock
Labels: Priority: 2 - High, PR: ready-for-review, PR: ready-for-test

#513 [CI] Fix utils test rounding error
  src/backend/__tests__/utils.test.ts
Labels: PR: ready-for-review

#505 [CI] Windows Release and Signing
  .github/workflows/release_windows.yml
  package.json
Labels: PR: ready-for-review

#516 [CI] Add caching to CI workflows
  .github/workflows/build.yml
  .github/workflows/codecheck.yml
  .github/workflows/lint.yml
  .github/workflows/release_flathub.yml
  .github/workflows/release_linux.yml
  .github/workflows/release_macOS.yml
  .github/workflows/submodules-are-merged.yml
  .github/workflows/test-e2e-dev.yml
  .github/workflows/test-e2e-packaged.yml
  .github/workflows/test.yml
Labels: PR: ready-for-review, PR: ready-for-test

#528 [Feat] Add remove from library option to game card
  public/locales/en/gamepage.json
  public/locales/en/translation.json
  src/backend/api/library.ts
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#530 [UI] Use cursor pointer for sidebar links
  src/frontend/components/UI/Sidebar/index.scss
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#529 [UI] Update metamask container to be position fixed
  src/frontend/ExtensionManager/index.module.scss
  src/frontend/components/UI/TopNavBar/index.module.scss
  src/frontend/index.scss
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#525 [FIX] Open game links when using proton on linux
  src/backend/game_config.ts
  src/backend/launcher.ts
  src/frontend/screens/Settings/components/SteamRuntime.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#555 [Tech] Update husky commands
  .husky/post-checkout
  .husky/post-merge
Labels: PR: Ready-For-Review

#545 [Fix] Windows game settings showing wine/crossover
  src/backend/main.ts
  src/frontend/components/UI/Collapsible/Collapsible.tsx
  src/frontend/screens/Settings/sections/GamesSettings/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test
