Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2023-05, with the labels that each got.

#292 [Fix] HP Store Manager
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/hyperplay/library.ts
Labels: PR: ready-for-review

#303 [CI] Add Flatpak and macOS M1 Builds
  .github/workflows/build.yml
  .github/workflows/flatpak-build.yml
  .gitignore
  flatpak/flathub.json
  flatpak/patches/aria2/working-build.patch
  flatpak/patches/p7zip/gcc10-conversion.patch
  flatpak/prepareFlatpak.js
  flatpak/templates/xyz.hyperplay.HyperPlay.metainfo.xml.template
  flatpak/templates/xyz.hyperplay.HyperPlay.yml.template
  flatpak/xyz.hyperplay.HyperPlay.desktop
  flatpak/xyz.hyperplay.HyperPlay.png
  package.json
Labels: PR: ready-for-review

#313 [UI] Add App Version to Settings
  src/frontend/components/UI/AppVersion/index.tsx
  src/frontend/components/UI/Sidebar/components/HeroicVersion/index.tsx
  src/frontend/screens/Settings/sections/GeneralSettings/index.tsx
  yarn.lock
Labels: PR: ready-for-review

#314 [Feat] Import with Recovery Phrase
  package.json
  src/frontend/App.tsx
  src/frontend/screens/MetaMaskHome/index.tsx
  src/frontend/screens/Onboarding/components/importOption/index.tsx
  src/frontend/screens/Onboarding/walletSelection/screens/import/index.tsx
  src/frontend/store/OnboardingStore.tsx
  yarn.lock
Labels: PR: ready-for-review

#287 [Feat] Pause Downloads Queue
  package.json
  public/locales/en/translation.json
  src/backend/api/downloadmanager.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/downloadmanager/ipc_handler.ts
  src/backend/downloadmanager/utils.ts
  src/backend/main.ts
  src/backend/storeManagers/gog/games.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/index.ts
  src/backend/storeManagers/legendary/games.ts
  src/backend/utils.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/frontend/assets/pause-icon.svg
  src/frontend/helpers/library.ts
  src/frontend/hooks/constants.ts
  src/frontend/hooks/hasStatus.ts
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
  src/frontend/screens/DownloadManager/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/constants.ts
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx
  src/frontend/types.ts
  yarn.lock
Labels: PR: ready-for-review, PR: ready-for-test

#321 [FIX] Auto Download Wine on macOS
  package.json
  src/backend/utils.ts
Labels: PR: ready-for-review

#333 [Fix] Hotfix
  src/backend/downloadmanager/utils.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/utils.ts
  src/common/types.ts
  src/frontend/hooks/constants.ts
  src/frontend/screens/Accessibility/index.css
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/constants.ts
  src/frontend/state/GlobalState.tsx
Labels: Priority: 1 - Highest, PR: ready-for-review, PR: ready-for-test

#330 Add e2e testing
  .dockerignore
  .eslintrc
  .github/workflows/test-e2e-dev.yml
  .github/workflows/test-e2e-packaged.yml
  README.md
  e2e/Dockerfile.test
  e2e/__specs__/api.spec.ts
  e2e/__specs__/common-setup.ts
  e2e/docker-compose.yml
  e2e/entrypoint.sh
  package.json
  src/backend/main.ts
  src/backend/online_monitor.ts
  tsconfig.eslint.json
  yarn.lock
Labels: PR: ready-for-review, PR: ready-for-test

#335 merge main 0.2.2
  package.json
  sign/notarize.js
  src/backend/__mocks__/test.zip
  src/backend/__tests__/utils.test.ts
  src/backend/api/misc.ts
  src/backend/downloadmanager/utils.ts
  src/backend/hyperplay_store_preload.ts
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/backend/storeManagers/hyperplay/utils.ts
  src/backend/storeManagers/index.ts
  src/backend/storeManagers/legendary/library.ts
  src/backend/utils.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/frontend/App.tsx
  src/frontend/StoreNavHandler/index.tsx
  src/frontend/helpers/index.ts
  src/frontend/hooks/constants.ts
  src/frontend/screens/Accessibility/index.css
  src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameSubMenu/index.tsx
  src/frontend/screens/Library/components/GameCard/constants.ts
  src/frontend/screens/Library/components/InstallModal/index.tsx
  src/frontend/screens/Library/index.tsx
  src/frontend/state/GlobalState.tsx
  yarn.lock
Labels: PR: ready-for-review

#337 [Fix] Handle Invalid Download Urls
  src/backend/storeManagers/hyperplay/library.ts
  src/backend/utils.ts
Labels: PR: ready-for-review

#338 [FIX] Unzip native macOS files
  package.json
  src/backend/__tests__/utils.test.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/backend/utils.ts
  src/frontend/components/UI/SearchBar/index.css
Labels: PR: ready-for-review, PR: ready-for-test

#327 [Feature] Update Game Cards
  package.json
  src/frontend/screens/Library/components/ContextMenu/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/GamesList/index.tsx
  src/frontend/screens/Library/index.css
  src/frontend/screens/Settings/index.tsx
  yarn.lock
Labels: PR: ready-for-review, PR: ready-for-test
