Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-03, with the labels that each got.

#777 [Summon Quest] Add LD flag, error handling, metrics events
  src/backend/main.ts
  src/backend/metrics/types.ts
Labels: PR: Ready-For-Review, Severity: 3 - Low

#779 [Chore] Update Lavamoat
  package.json
  yarn.lock
Labels: PR: Ready-For-Review

#780 [Chore] Update vite to v5
  package.json
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#766 [FIX] Games Auto Update
  src/backend/main.ts
  src/backend/storeManagers/index.ts
  src/backend/wiki_game_info/pcgamingwiki/utils.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#789 [FIX] GPTK Filtering and download
  src/backend/main.ts
  src/backend/utils.ts
  src/backend/wine/manager/utils.ts
  src/frontend/screens/WineManager/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#784 [FEAT] Show System information on Log Screen
  package.json
  public/locales/en/gamepage.json
  public/locales/en/login.json
  public/locales/en/translation.json
  src/backend/api/settings.ts
  src/backend/launcher.ts
  src/backend/logger/logger.ts
  src/backend/main.ts
  src/backend/utils.ts
  src/backend/utils/helperBinaries/index.ts
  src/backend/utils/inet/downloader/index.ts
  src/backend/utils/ipc_handler.ts
  src/backend/utils/os/path/index.ts
  src/backend/utils/os/processes/index.ts
  src/backend/utils/systeminfo/gpu/index.ts
  src/backend/utils/systeminfo/gpu/linux.ts
  src/backend/utils/systeminfo/gpu/pci_ids.ts
  src/backend/utils/systeminfo/gpu/windows.ts
  src/backend/utils/systeminfo/index.ts
  src/backend/utils/systeminfo/memory/index.ts
  src/backend/utils/systeminfo/memory/linux.ts
  src/backend/utils/systeminfo/memory/macos.ts
  src/backend/utils/systeminfo/memory/windows.ts
  src/backend/utils/systeminfo/osInfo/index.ts
  src/backend/utils/systeminfo/osInfo/linux.ts
  src/backend/utils/systeminfo/osInfo/windows.ts
  src/backend/utils/systeminfo/steamDeck.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/assets/amd-logo.svg
  src/frontend/assets/intel-logo.svg
  src/frontend/assets/nvidia-logo.svg
  src/frontend/assets/steam-deck-logo.svg
  src/frontend/helpers/index.ts
  src/frontend/hooks/useAwaited.ts
  src/frontend/screens/Login/index.tsx
  src/frontend/screens/Settings/components/UseDGPU.tsx
  src/frontend/screens/Settings/index.tsx
  src/frontend/screens/Settings/sections/LogSettings/index.css
  src/frontend/screens/Settings/sections/SystemInfo/cpu.tsx
  src/frontend/screens/Settings/sections/SystemInfo/gpu.tsx
  src/frontend/screens/Settings/sections/SystemInfo/index.scss
  src/frontend/screens/Settings/sections/SystemInfo/index.tsx
  src/frontend/screens/Settings/sections/SystemInfo/memory.tsx
  src/frontend/screens/Settings/sections/SystemInfo/os.tsx
  src/frontend/screens/Settings/sections/SystemInfo/software.tsx
  src/frontend/screens/Settings/sections/SystemInfo/vendorLogo.tsx
  src/frontend/screens/Settings/sections/index.tsx
  tsconfig.json
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#782 Feat: Advanced Options
  package.json
  src/frontend/screens/Onboarding/components/importOption/index.module.scss
  src/frontend/screens/Onboarding/components/importOption/index.tsx
  src/frontend/screens/Onboarding/walletSelection/screens/import/components/ImportAndCreateOptions/index.module.scss
  src/frontend/screens/Onboarding/walletSelection/screens/import/components/ImportAndCreateOptions/index.tsx
  src/frontend/screens/Onboarding/walletSelection/screens/import/index.tsx
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#745 [Windows] Allow more install options
  package.json
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#819 [Chore] Remove Unused files and update Readme
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
  Dockerfile
  README.md
  appveyor.yml
  downloadCount.js
Labels: PR: Ready-For-Review

#824 [Chore] Update follow-redirect parent deps
  package.json
  src/backend/storeManagers/hyperplay/utils.ts
  src/common/types.ts
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#820 [CHORE] Flatpak CI build Update
  .github/workflows/flatpak-build.yml
  flatpak/patches/gamemode/disable-pidfd.patch
  flatpak/templates/xyz.hyperplay.HyperPlay.yml.template
Labels: PR: Ready-For-Review
