Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-04, with the labels that each got.

#816 [UI/UX] Improve Log screen with game list and categories
  public/locales/en/translation.json
  src/backend/api/settings.ts
  src/backend/launcher.ts
  src/backend/logger/__tests__/logfile.test.ts
  src/backend/logger/ipc_handler.ts
  src/backend/logger/logfile.ts
  src/backend/storeManagers/gog/user.ts
  src/backend/storeManagers/nile/user.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/frontend/screens/Settings/sections/LogSettings/index.css
  src/frontend/screens/Settings/sections/LogSettings/index.tsx
  tsconfig.json
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#831 [FIX] Check disk space not working
  vite.config.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#830 [CI] Use Native Notarise method from Electron builder
  package.json
  sign/notarize.js
  src/frontend/screens/Login/index.tsx
  src/frontend/screens/WebView/index.tsx
  yarn.lock
Labels: PR: Ready-For-Review

#840 [Chore] 0.13.0
  package.json
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#845 [Fix] Fix White Screen on Windows build
  package.json
  vite.config.ts
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test, Severity: 0 - Critical

#856 [FIX] Search bar item click navigation
  src/frontend/components/UI/SearchBar/index.tsx
Labels: Type: Bug, PR: Ready-For-Test, Severity: 3 - Low

#860 [Chore] Update json5 to 2.2.3
  yarn.lock
Labels: PR: Ready-For-Review

#857 [Feat] Add go back and go forward arrows to browser games
  src/frontend/OverlayManager/index.module.scss
  src/frontend/OverlayManager/index.tsx
  src/frontend/components/UI/WebviewControls/index.tsx
Labels: PR: Ready-For-Test

#861 [TECH] Speed Up Big Libraries loading
  src/backend/api/misc.ts
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/backend/storeManagers/index.ts
  src/backend/storeManagers/sideload/library.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/state/libraryState.ts
Labels: PR: Ready-For-Review

#848 Send auth cookie with license validate request
  src/backend/constants.ts
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: Ready-For-Test

#859 [UI/UX] Show store links on navbar on all pages and adjust it to small window sizes
  src/backend/__tests__/main_window.test.ts
  src/backend/main_window.ts
  src/frontend/components/UI/SearchBar/index.css
  src/frontend/components/UI/TopNavBar/index.module.scss
  src/frontend/components/UI/TopNavBar/index.tsx
  src/frontend/screens/Library/components/LibraryTopBar/index.module.scss
Labels: Priority: 4 - Low, PR: Ready-For-Test

#867 [Fix] Auth preload
  package.json
  src/backend/auth_provider_preload.ts
Labels: Priority: 1 - Highest, PR: Ready-For-Review

#649 Add token gated channels
  package.json
  src/backend/api/downloadmanager.ts
  src/backend/downloadmanager/utils.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/hyperplay/utils.ts
  src/common/constants.ts
  src/common/types.ts
  src/common/types/game_manager.ts
  src/frontend/ExtensionManager/index.module.scss
  src/frontend/ExtensionManager/index.tsx
  src/frontend/helpers/library.ts
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.scss
  src/frontend/screens/Library/components/InstallModal/index.tsx
  yarn.lock
Labels: PR: Ready-For-Review
