Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-11, with the labels that each got.

#1127 [FIX] Extract Progress for Base Game
  src/backend/ipcHandlers/mods.ts
  src/common/types.ts
  src/frontend/components/UI/DownloadToastManager/index.tsx
Labels: PR: Ready-For-Test

#1136 [UI] Add portfolio sublinks
  package.json
  public/locales/en/translation.json
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/index.module.scss
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/index.tsx
  src/frontend/OverlayManager/Overlay/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1142 [Fix] Improve error logs for license key validate and get auth
  public/locales/en/translation.json
  src/backend/auth.ts
  src/frontend/components/UI/AccessCodeInput/index.tsx
Labels: PR: Ready-For-Review

#1137 [Feat] Add overlay marketplaces
  public/locales/en/translation.json
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/MarketplaceNavItem/MarketplaceSublinks/index.tsx
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/MarketplaceNavItem/index.tsx
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/PortfolioNavItem/index.tsx
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/index.tsx
  src/frontend/OverlayManager/Overlay/index.tsx
  src/frontend/screens/WebView/index.css
  src/frontend/screens/WebView/index.tsx
Labels: PR: Ready-For-Test

#1055 [UI] Cleanup App and Game Settings
  public/locales/en/translation.json
  src/backend/utils.ts
  src/common/types.ts
  src/frontend/components/UI/TextInputField/index.scss
  src/frontend/components/UI/TextInputField/index.tsx
  src/frontend/screens/Settings/components/AltGOGdlBin.tsx
  src/frontend/screens/Settings/components/AltLegendaryBin.tsx
  src/frontend/screens/Settings/components/BattlEyeRuntime.tsx
  src/frontend/screens/Settings/components/EacRuntime.tsx
  src/frontend/screens/Settings/components/EgsSettings.tsx
  src/frontend/screens/Settings/components/IgnoreGameUpdates.tsx
  src/frontend/screens/Settings/components/index.ts
  src/frontend/screens/Settings/index.scss
  src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
  src/frontend/screens/Settings/sections/GeneralSettings/index.tsx
Labels: Priority: 4 - Low, PR: Ready-For-Test

#1143 [Fix] toggle overlay
  package.json
  src/backend/main.ts
  src/backend/overlay/api.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/OverlayManager/Overlay/index.tsx
  src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1087 [FEAT] Client IPDT Patching implementation
  .env.example
  .github/workflows/build-mac-arm64.yml
  .github/workflows/build.yml
  .github/workflows/flatpak-build.yml
  .github/workflows/release_linux.yml
  .github/workflows/release_macOS.yml
  .github/workflows/release_snap.yml
  .github/workflows/release_windows.yml
  .github/workflows/test.yml
  .gitignore
  package.json
  public/locales/en/gamepage.json
  public/locales/en/translation.json
  src/backend/__tests__/constants.test.ts
  src/backend/__tests__/main_window.test.ts
  src/backend/__tests__/utils.test.ts
  src/backend/api/downloadmanager.ts
  src/backend/constants.ts
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/flags/flags.ts
  src/backend/ipcHandlers/launchdarkly.ts
  src/backend/logger/__tests__/logfile.test.ts
  src/backend/logger/__tests__/logger.test.ts
  src/backend/main.ts
  src/backend/metrics/types.ts
  src/backend/shortcuts/nonesteamgame/__tests__/nonesteamgame.test.ts
  src/backend/storeManagers/hyperplay/__tests__/utils.test.ts
  src/backend/storeManagers/hyperplay/constants.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/hyperplay/utils.ts
  src/backend/tray_icon/__tests__/tray_icon.test.ts
  src/backend/utils/__tests__/compatibility_layers.test.ts
  src/backend/vite_constants.ts
  src/backend/wiki_game_info/__tests__/wiki_game_info.test.ts
  src/backend/wiki_game_info/applegamingwiki/__tests__/utils.test.ts
  src/backend/wiki_game_info/pcgamingwiki/__tests__/utils.test.ts
  src/common/types.ts
  src/frontend/components/UI/DownloadToastManager/index.tsx
  src/frontend/components/UI/StopInstallationModal/index.tsx
  src/frontend/helpers/index.ts
  src/frontend/hooks/constants.ts
  src/frontend/hooks/useGetDownloadStatusText.ts
  src/frontend/index.tsx
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/constants.ts
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/constants.ts
  src/frontend/state/GlobalState.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#1146 [FIX] Download Action after canceling update from DM
  package.json
  public/locales/en/translation.json
  src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
  src/frontend/screens/Game/GamePage/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1124 [UI/UX] Add completed quests tab
  package.json
  src/common/types.ts
  src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.module.scss
  src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.tsx
  src/frontend/components/UI/QuestsViewer/index.tsx
  src/frontend/hooks/useGetQuest.ts
  src/frontend/hooks/useGetQuestStates.ts
  src/frontend/hooks/useGetRewards.ts
  src/frontend/hooks/useGetUserPlayStreak.ts
  src/frontend/hooks/useSyncInterval.ts
  src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1132 feat(quest-details): add claim in quest page
  package.json
  public/locales/en/translation.json
  src/frontend/OverlayManager/Overlay/index.module.scss
  src/frontend/OverlayManager/Overlay/index.tsx
  src/frontend/components/UI/QuestDetails/index.tsx
  src/frontend/components/UI/QuestRewardClaimedToast/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.module.scss
  src/frontend/components/UI/QuestsViewer/index.tsx
  src/frontend/index.tsx
  src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.module.scss
  src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.module.scss
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
  src/frontend/screens/Quests/index.module.scss
  src/frontend/screens/Quests/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1111 [Fix] Keep playstreak quests in sync
  package.json
  src/backend/main.ts
  src/frontend/OverlayManager/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1150 [UX] Disable portfolio in overlay for incompatible wallet providers
  public/locales/en/translation.json
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/PortfolioNavItem/index.tsx
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/index.module.scss
  yarn.lock
Labels: PR: Ready-For-Test

#1149 [Fix] ext lock connect
  package.json
  src/backend/proxy/providerPreload.ts
  src/common/types.ts
  src/frontend/ExtensionHandler/index.tsx
  src/frontend/OverlayManager/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1148 [Feat] Add patching speed check
  package.json
  src/backend/metrics/types.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/hyperplay/types.ts
  yarn.lock
Labels: PR: Ready-For-Test

#1152 [Fix] UI - overflow of quests container when logged out in overlay
  src/frontend/components/UI/QuestsViewer/index.module.scss
Labels: PR: Ready-For-Test

#1153 [Fix] Network add in portfolio swap
  src/backend/proxy/providerPreload.ts
Labels: PR: Ready-For-Test

#1157 [CI] Update upload-artifact action to v4
  .github/workflows/build.yml
  .github/workflows/flatpak-build.yml
Labels: PR: Ready-For-Review

#1162 [FIX] Update Game status after finishing playing and not logged in
  package.json
  src/backend/main.ts
  src/backend/utils/quests.ts
Labels: PR: Ready-For-Test

#1160 [UX] Update compatibility dialog to be non-modal
  src/frontend/components/UI/Dialog/components/Dialog.tsx
  src/frontend/components/UI/Dialog/index.css
  src/frontend/components/UI/DialogHandler/components/MessageBoxModal/index.tsx
  src/frontend/components/UI/DialogHandler/index.tsx
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/frontend/helpers/library.ts
  src/frontend/types.ts
Labels: PR: Ready-For-Test
