Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-08, with the labels that each got.

#983 [FIX] isGameAvailable fail because of backslashes for windows games on mac and linux
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: Ready-For-Test

#982 [FEAT] Show warning on close the app if a game is opened.
  src/frontend/state/GlobalState.tsx
Labels: PR: Ready-For-Test

#952 [Fix] Stop game multiple processes
  src/backend/launcher.ts
  src/backend/storeManagers/hyperplay/games.ts
  yarn.lock
Labels: PR: Ready-For-Test

#979 [Fix] Decimals null check in useGetRewards
  package.json
  src/frontend/hooks/useGetRewards.ts
Labels: PR: Ready-For-Review

#980 [FIX] Epic Games tracking on Windows
  src/backend/launcher.ts
  src/backend/main.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/TimeContainer/index.tsx
Labels: PR: Ready-For-Test

#984 [Feat] Add window.api.navigate to store preload, add quest routes
  src/backend/api/misc.ts
  src/backend/hyperplay_store_preload.ts
  src/backend/main.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/App.tsx
  src/frontend/NavigateListener/index.tsx
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
  src/frontend/screens/Quests/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#985 feat(quest): add claim flags for each reward type
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
Labels: PR: Ready-For-Review

#987 [FIX] Launching HP games on mac and linux
  src/backend/launcher.ts
  yarn.lock
Labels: Priority: 1 - Highest, PR: Ready-For-Test

#988 [FIX] Show Wallet onboard when launching web3 game from GamePage
  src/frontend/screens/Game/GamePage/index.tsx
Labels: PR: Ready-For-Test, Severity: 2 - Medium

#991 [FIX] CI: AUR Publishing
  .github/workflows/release_aur.yml
Labels: PR: Ready-For-Review

#996 [Fix] no quests message
  public/locales/en/translation.json
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
Labels: PR: Ready-For-Review

#986 [Chore] Upgrade dependencies
  yarn.lock
Labels: PR: Ready-For-Test

#995 [FIX] Deal with Epic games listing from Quests Page
  src/backend/api/library.ts
  src/backend/launcher.ts
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/utils.ts
  src/backend/storeManagers/legendary/games.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/helpers/index.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
Labels: Priority: 1 - Highest, PR: Ready-For-Review

#998 [UX] sync playsession every minute
  package.json
  src/backend/api/questsAchievements.ts
  src/backend/launcher.ts
  src/backend/main.ts
  src/backend/utils/shouldOpenOverlay.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
  src/frontend/helpers/getPlaystreakArgsFromQuestData.ts
  src/frontend/hooks/useSyncInterval.ts
  src/frontend/hooks/useTrackQuestViewed.ts
Labels: PR: Ready-For-Test

#997 [Feat] add search bar to quest summary table
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
  src/frontend/hooks/useGetQuest.ts
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#989 [Tech] Remove references to valistBaseApiUrlv1
  src/backend/storeManagers/hyperplay/games.ts
  src/common/constants.ts
  src/frontend/helpers/library.ts
Labels: PR: Ready-For-Review, Type: Tech

#1008 [UI] fix total claimed g7 credits text
  public/locales/en/translation.json
  src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.tsx
Labels: PR: Ready-For-Review

#1002 [Fix] should show extension
  src/frontend/OverlayManager/Overlay/index.tsx
Labels: PR: Ready-For-Test

#1004 [Feat] Add g7 credits modal
  package.json
  public/locales/en/translation.json
  src/frontend/assets/g7PortalScreenshot.png
  src/frontend/components/UI/G7CreditsModal/index.module.scss
  src/frontend/components/UI/G7CreditsModal/index.tsx
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
  src/frontend/screens/Quests/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1017 [Fix] epic/gog manual updates
  src/frontend/state/GameUpdateState.ts
Labels: PR: Ready-For-Test

#1003 feat(quest): add onchain reward confirmation modal
  public/locales/en/translation.json
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/components/ConfirmClaimModal/index.module.scss
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/components/ConfirmClaimModal/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
Labels: PR: Ready-For-Test

#1018 [Fix] regression on launching overlay for epic forwarder listings
  package.json
  src/backend/utils/shouldOpenOverlay.ts
  yarn.lock
Labels: PR: Ready-For-Test

#1007 feat(quest): add support for sending completed claim to API
  src/backend/api/questsAchievements.ts
  src/backend/ipcHandlers/quests.ts
  src/backend/utils/fetch_with_cookie.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/rewards/mintReward.ts
Labels: PR: Ready-For-Test

#1015 [Feat] Show num claims left for each reward
  package.json
  src/common/types.ts
  src/frontend/hooks/useGetRewards.ts
Labels: PR: Ready-For-Test

#1026 [Fix] erc1155 numClaimsLeft
  src/common/types.ts
  src/frontend/hooks/useGetRewards.ts
Labels: PR: Ready-For-Test

#1030 [CI] disable e2e tests
  .github/workflows/test-e2e-dev.yml
  .github/workflows/test-e2e-packaged.yml
Labels: PR: Ready-For-Review

#1028 [UI] Mod dialog UI changes
  src/frontend/components/UI/AccessCodeInput/index.module.scss
  src/frontend/components/UI/AccessCodeInput/index.tsx
  src/frontend/screens/Library/components/InstallModal/ModDialog/ModDialog.module.scss
  src/frontend/screens/Library/components/InstallModal/ModDialog/constants.ts
  src/frontend/screens/Library/components/InstallModal/ModDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/index.tsx
Labels: PR: Ready-For-Review

#1032 [Tech] update playsession
  package.json
  src/backend/main.ts
Labels: PR: Ready-For-Test

#1036 fix(quest-claim): balance check race condition
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
Labels: PR: Ready-For-Test

#1037 feat(quest-claim): show error ui for claim errors
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
Labels: PR: Ready-For-Review

#1000 [TECH] Auto-Update improvements
  .github/workflows/flatpak-build.yml
  public/locales/en/gamepage.json
  public/locales/en/login.json
  public/locales/en/translation.json
  src/backend/main.ts
  src/backend/updater.ts
Labels: Priority: 2 - High, PR: Ready-For-Review

#1043 [Fix] Showing Install Path for Browser games
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
Labels: PR: Ready-For-Test

#1013 [TECH] Upgrade Electron and other Dev Dependencies
  .husky/post-checkout
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  i18next-parser.config.js
  package.json
  src/backend/config.ts
  src/backend/main.ts
  src/backend/storeManagers/gog/library.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/SentryHandler/index.tsx
  src/frontend/components/UI/ChannelNameSelection/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
  src/frontend/config.ts
  src/frontend/screens/Library/index.tsx
  src/frontend/state/AchievementState.ts
  src/frontend/state/OverlayState.ts
  yarn.lock
Labels: Priority: 3 - Medium, PR: Ready-For-Test

#1048 [CI]: Workflow maintenance
  .github/workflows/build-mac-arm64.yml
  .github/workflows/build.yml
  .github/workflows/codecheck.yml
  .github/workflows/flatpak-build.yml
  .github/workflows/lint.yml
  .github/workflows/release_flathub.yml
  .github/workflows/release_linux.yml
  .github/workflows/release_macOS.yml
  .github/workflows/release_snap.yml
  .github/workflows/release_windows.yml
  .github/workflows/test-e2e-dev.yml
  .github/workflows/test-e2e-packaged.yml
  .github/workflows/test.yml
Labels: PR: Ready-For-Review

#1029 [Chore] update readme local development section
  README.md
  dev/rmOptionalDependencies.js
  package.json
Labels: PR: Ready-For-Review

#1014 [TECH] Upgrade React and other frontend packages
  package.json
  patches/isomorphic-fetch+3.0.0.patch
  src/frontend/helpers/getRewardCategory.ts
  src/frontend/index.tsx
  src/frontend/screens/Achievements/utils.ts
  src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test
