Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-09, with the labels that each got.

#954 feat(overlay): add wallet disconnected message
  public/locales/en/translation.json
  src/frontend/OverlayManager/Overlay/index.tsx
Labels: Priority: 4 - Low, PR: Ready-For-Test

#1052 [FIX] HyperPlay fails if the game default channel is not expected
  src/backend/downloadmanager/downloadqueue.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/frontend/screens/Game/GamePage/index.tsx
Labels: PR: Ready-For-Test

#1040 [Fix] repeat external task claims showing sync instead of claim
  package.json
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
Labels: PR: Ready-For-Test

#1054 [FIX] Don't show Game Settings for Browser games on game card
  src/frontend/screens/Library/components/GameCard/index.tsx
Labels: PR: Ready-For-Test

#1053 [Fix] hide, unhide, favorite, and unfavorite game
  src/common/types.ts
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/GamesList/index.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/state/__tests__/libraryState.test.ts
  src/frontend/state/libraryState.ts
Labels: PR: Ready-For-Test

#1057 [Tech] improve playsession POST logs
  src/backend/utils/quests.ts
Labels: PR: Ready-For-Review

#1046 [TECH] Logs Cleanup
  src/backend/anticheat/utils.ts
  src/backend/launcher.ts
  src/backend/logger/logger.ts
  src/backend/main.ts
  src/backend/storeManagers/gog/library.ts
  src/backend/storeManagers/gog/user.ts
  src/backend/utils/aborthandler/aborthandler.ts
Labels: PR: Ready-For-Test

#1039 [FIX] Check isAvailable when using TargetEXE Setting
  src/backend/storeManagers/gog/games.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/legendary/games.ts
  src/backend/storeManagers/sideload/games.ts
  src/common/types/game_manager.ts
Labels: Priority: 5 - Lowest, PR: Ready-For-Test

#1062 [FIX] Get Install Info failing because of WebGL platform
  .vscode/settings.json
  public/locales/en/gamepage.json
  src/backend/storeManagers/hyperplay/utils.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
Labels: Priority: 1 - Highest, PR: Ready-For-Test, Severity: 1 - High

#1038 [Tech] Refactor to use quests ui quest details
  package.json
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/components/ConfirmClaimModal/index.module.scss
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/components/ConfirmClaimModal/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.module.scss
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/rewards/claimPoints.ts
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/rewards/completeExternalTask.ts
  src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/rewards/mintReward.ts
  src/frontend/components/UI/QuestsViewer/index.module.scss
  src/frontend/components/UI/QuestsViewer/index.tsx
  src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1042 [Feat] add import game folder
  public/locales/en/translation.json
  src/backend/api/library.ts
  src/backend/ipcHandlers/importGameFolder.ts
  src/backend/ipcHandlers/index.ts
  src/backend/storeManagers/hyperplay/library.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/ImportGameFolder/index.module.scss
  src/frontend/components/UI/ImportGameFolder/index.tsx
  src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
Labels: PR: Ready-For-Test

#1063 [UI] Make Download Toast Draggable
  package.json
  src/frontend/components/UI/DownloadToastManager/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1051 [Feat] One-click Install Steam on macOS
  public/locales/en/translation.json
  src/backend/api/library.ts
  src/backend/ipcHandlers/mods.ts
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/tools.ts
  src/backend/utils.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/Dialog/index.css
  src/frontend/screens/Library/components/SteamInstall/SteamInstallButton.tsx
  src/frontend/screens/Library/components/SteamInstall/SteamInstallDialog.tsx
  src/frontend/screens/Library/index.module.scss
  src/frontend/screens/Library/index.tsx
Labels: Priority: 2 - High, PR: Ready-For-Test

#1045 [FIX] Improve default Compatibility Layer setup
  src/backend/config.ts
  src/backend/main.ts
  src/backend/storeManagers/gog/setup.ts
  src/backend/utils.ts
  src/backend/utils/compatibility_layers.ts
  yarn.lock
Labels: Priority: 2 - High, PR: Ready-For-Test

#1073 [FIX] Don't update games with removed platform build
  package.json
  src/backend/storeManagers/hyperplay/library.ts
Labels: PR: Ready-For-Test

#1041 [Feat] check g7 connection status
  package.json
  public/locales/en/translation.json
  src/backend/api/questsAchievements.ts
  src/backend/ipcHandlers/quests.ts
  src/backend/main.ts
  src/backend/utils/quests.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/QuestsViewer/index.tsx
  src/frontend/hooks/useCheckG7ConnectionStatus.ts
  src/frontend/hooks/useGetG7UserCredits.ts
  yarn.lock
Labels: PR: Ready-For-Test

#1077 [FIX] Fix Claim Modal translations keys
  public/locales/en/translation.json
  src/frontend/components/UI/QuestsViewer/index.tsx
Labels: PR: Ready-For-Test

#1090 [FIX] Unknown platform name on sideload launch
  src/backend/utils.ts
Labels: PR: Ready-For-Review

#1076 [Fix] install modal folder
  src/frontend/components/UI/Dialog/index.css
  src/frontend/components/UI/TextInputField/index.tsx
  src/frontend/components/UI/TextInputWithIconField/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.module.scss
Labels: PR: Ready-For-Test

#1079 fix(overlay): update layout to improve UX on lower viewports
  package.json
  public/locales/en/translation.json
  src/frontend/ExtensionManager/components/ExtensionContents/index.tsx
  src/frontend/ExtensionManager/index.module.scss
  src/frontend/ExtensionManager/index.tsx
  src/frontend/OverlayManager/Overlay/index.module.scss
  src/frontend/OverlayManager/Overlay/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.module.scss
  src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.tsx
  src/frontend/components/UI/QuestsViewer/index.module.scss
  src/frontend/components/UI/QuestsViewer/index.tsx
  yarn.lock
Labels: PR: Ready-For-Test

#1088 fix(overlay): set autoBind true to AuthState makeAutoObservable
  src/frontend/state/authState.ts
Labels: PR: Ready-For-Test

#1094 fix(overlay): show notification window on transaction request
  package.json
  src/frontend/ExtensionManager/components/ExtensionContents/index.tsx
  src/frontend/ExtensionManager/index.tsx
  src/frontend/OverlayManager/Overlay/index.module.scss
Labels: PR: Ready-For-Test

#1083 [FIX] RunWineCommand not working for Non-HyperPlay Games
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/legendary/games.ts
  src/backend/storeManagers/legendary/setup.ts
  src/backend/utils/compatibility_layers.ts
Labels: PR: Ready-For-Test

#1078 [CI] Add i18n Parser Check
  .github/workflows/translations_parser.yml
Labels: PR: Ready-For-Review
