Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-05, with the labels that each got.

#876 [TECH] Remove Experimental Features
  src/common/types.ts
  src/frontend/screens/Settings/components/ExperimentalFeatures.tsx
  src/frontend/screens/Settings/components/index.ts
  src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
  src/frontend/state/ContextProvider.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/types.ts
Labels: PR: Ready-For-Review

#874 [Chore] Keep app data on uninstall
  package.json
Labels: PR: Ready-For-Test

#869 [Feat] Support Launch arguments from EXE
  src/backend/__tests__/utils.test.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/backend/utils.ts
Labels: Priority: 2 - High, PR: Ready-For-Test

#864 [FIX] Don't fail to launch if Steam Runtime was not found
  flatpak/templates/xyz.hyperplay.HyperPlay.yml.template
  public/locales/en/translation.json
  src/backend/launcher.ts
Labels: PR: Ready-For-Test

#883 tech: use native UI for newsletter subscription
  public/locales/en/translation.json
  src/backend/email_modal_provider_preload.ts
  src/backend/main.ts
  src/common/types/electron_store.ts
  src/frontend/components/UI/EmailSubscriptionModal/index.module.scss
  src/frontend/components/UI/EmailSubscriptionModal/index.tsx
  src/frontend/constants.ts
  src/frontend/helpers/electronStores.ts
  src/frontend/state/EmailSubscriptionState.ts
  vite.config.ts
Labels: PR: Ready-For-Test

#875 [FIX] install distributables Status and other UI fixes
  public/locales/en/gamepage.json
  src/frontend/components/UI/DownloadToastManager/index.tsx
  src/frontend/hooks/constants.ts
  src/frontend/hooks/useGetDownloadStatusText.ts
  src/frontend/screens/Game/GamePage/index.scss
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Game/GameSubMenu/index.css
  src/frontend/state/GlobalState.tsx
Labels: PR: Ready-For-Test

#886 [Fix] Ignore auto update for hp games if they are access code gated
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/storeManagers/index.ts
Labels: PR: Ready-For-Test

#888 [Fix] Fix sui support
  package.json
  public/extensions/MetaMask_v10.22.2/common-0.js
  yarn.lock
Labels: PR: Ready-For-Test

#889 [Fix] Update for non token gated games
  src/backend/downloadmanager/downloadqueue.ts
  src/frontend/helpers/library.ts
  src/frontend/state/libraryState.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#890 [UI] Make loader bg transparent in library
  src/frontend/components/UI/UpdateComponent/index.css
Labels: Priority: 4 - Low, PR: Ready-For-Test

#895 [Fix] Snap support proxy server
  package.json
  yarn.lock
Labels: PR: Ready-For-Review

#844 [Tech] Use DNS text queries to resolve PCI IDs (#3528)
  src/backend/api/misc.ts
  src/backend/main.ts
  src/backend/utils.ts
  src/backend/utils/systeminfo/gpu/pci_ids.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/ErrorComponent/index.tsx
  src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
Labels: PR: Ready-For-Test

#905 [Fix] browser game mm links
  package.json
  src/backend/constants.ts
  src/backend/constants/folders.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/backend/utils/hyperplay_api.ts
  src/backend/wine/runtimes/runtimes.ts
  yarn.lock
Labels: PR: Ready-For-Review

#908 [Fix] update mm
  package.json
  public/extensions/MetaMask_v10.22.2/common-0.js
  public/extensions/MetaMask_v10.22.2/manifest.json
  public/extensions/MetaMask_v10.22.2/ui-6.js
  public/extensions/MetaMask_v10.22.2/ui-9.js
Labels: PR: Ready-For-Test

#910 [Fix] Upgrade ethers to fix MM extension incompatibility
  package.json
  yarn.lock
Labels: Priority: 1 - Highest

#909 [FIX] Epic Webview Login
  src/backend/main.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#903 [FIX] HyperPlay logo and Badge not showing
  src/frontend/components/UI/TopNavBar/index.module.scss
Labels: Type: Bug, PR: Ready-For-Test, Severity: 3 - Low

#913 [Fix] Remove SRP direct link option
  package.json
  src/frontend/App.tsx
  src/frontend/screens/Onboarding/walletSelection/screens/import/components/ImportAndCreateOptions/index.tsx
Labels: Type: Bug, PR: Ready-For-Review, Severity: 1 - High
