Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-02, with the labels that each got.

#699 [FEAT] Offline improvements
  public/locales/en/gamepage.json
  public/locales/en/login.json
  public/locales/en/translation.json
  src/backend/updater.ts
  src/frontend/App.tsx
  src/frontend/ExtensionManager/index.tsx
  src/frontend/components/UI/OfflineMessage/index.scss
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.css
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/frontend/screens/Library/index.tsx
  src/frontend/screens/WebView/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#660 [TECH]: add support for ui lib with Mantine v7
  package.json
  src/frontend/components/UI/TopNavBar/index.module.scss
  src/frontend/index.tsx
  src/frontend/screens/Achievements/AchievementsLayout/index.tsx
  src/frontend/screens/Library/components/LibraryTopBar/index.module.scss
  src/frontend/screens/Library/components/LibraryTopBar/index.tsx
  src/frontend/screens/Settings/index.scss
  src/frontend/screens/Settings/index.tsx
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#716 [FIX] HP Games import
  public/locales/en/translation.json
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#721 [FIX] Check if game is available on game launch
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#719 [TECH]: update sign-in flow
  package.json
  public/locales/en/translation.json
  src/backend/__tests__/protocol.test.ts
  src/backend/api/auth.ts
  src/backend/api/misc.ts
  src/backend/auth_provider_preload.ts
  src/backend/ipcHandlers/auth.ts
  src/backend/main.ts
  src/backend/protocol.ts
  src/backend/transparent_body_preload.ts
  src/common/constants.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/App.tsx
  src/frontend/components/UI/AccountDropdown/index.module.scss
  src/frontend/components/UI/AccountDropdown/index.tsx
  src/frontend/components/UI/AuthModal/index.tsx
  src/frontend/components/UI/EmailVerifiedModal/index.tsx
  src/frontend/components/UI/TopNavBar/index.tsx
  src/frontend/components/UI/Wallet/index.tsx
  src/frontend/hooks/useAuthSession.ts
  vite.config.ts
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#742 [UX] Use download folder install path for .temp
  src/backend/storeManagers/hyperplay/games.ts
Labels: Priority: 2 - High

#755 [CI] Fix macOS release workflow
  .github/workflows/release_macOS.yml
  merge-yml.js
  package.json
Labels: PR: Ready-For-Review

#763 feat: add email subscription modal
  .env.example
  src/backend/api/misc.ts
  src/backend/email_modal_provider_preload.ts
  src/backend/main.ts
  src/common/constants.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types/electron_store.ts
  src/frontend/App.tsx
  src/frontend/components/UI/EmailSubscriptionModal/index.module.scss
  src/frontend/components/UI/EmailSubscriptionModal/index.tsx
  src/frontend/screens/Onboarding/walletSelection/index.tsx
  src/frontend/state/EmailSubscriptionState.ts
  src/frontend/state/authState.ts
  vite.config.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#761 [UX] Improve Compatibility layer setup and handling
  public/locales/en/gamepage.json
  public/locales/en/login.json
  public/locales/en/translation.json
  src/backend/launcher.ts
  src/backend/main.ts
  src/backend/tools.ts
  src/backend/utils.ts
  src/frontend/components/UI/DialogHandler/components/MessageBoxModal/index.tsx
  src/frontend/components/UI/DialogHandler/index.tsx
  src/frontend/components/UI/DownloadToastManager/index.tsx
  src/frontend/helpers/library.ts
  src/frontend/screens/Game/GamePage/index.tsx
  src/frontend/screens/Library/components/GameCard/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.module.scss
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/state/GlobalState.tsx
  src/frontend/styles/_colors.scss
  src/frontend/types.ts
Labels: Priority: 1 - Highest, PR: Ready-For-Review, PR: Ready-For-Test

#765 Add auto launch HyperPlay option
  package.json
  public/locales/en/gamepage.json
  public/locales/en/login.json
  public/locales/en/translation.json
  src/backend/api/settings.ts
  src/backend/main.ts
  src/backend/utils/auto_launch.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
  src/frontend/screens/Settings/components/AutoLaunchHyperPlay.tsx
  src/frontend/screens/Settings/sections/GeneralSettings/index.tsx
  yarn.lock
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#775 [Log] Remove duplicated log
  src/backend/main.ts
Labels: PR: Ready-For-Review

#774 [Fix] Prevent wine install on windows
  src/backend/utils.ts
  src/backend/wine/manager/ipc_handler.ts
  src/backend/wine/manager/utils.ts
Labels: PR: Ready-For-Review

#768 [FIX] Install Event Tracking
  src/backend/downloadmanager/utils.ts
Labels: PR: Ready-For-Review
