Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2024-12, with the labels that each got.

#1167 [Metrics] Use property session id generated each app session
  src/backend/metrics/metrics.ts
Labels: PR: Ready-For-Test

#1173 [Metrics] improve overlay, portfolio, and marketplace metrics
  src/backend/metrics/types.ts
  src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/index.tsx
  src/frontend/components/UI/AccountDropdown/index.tsx
  src/frontend/screens/MetaMaskPortfolio/index.tsx
Labels: PR: Ready-For-Test

#1163 [UI] Welcome modal update
  public/locales/en/translation.json
  src/frontend/assets/diamond.svg
  src/frontend/components/UI/LanguageSelector/index.tsx
  src/frontend/screens/Onboarding/index.module.scss
  src/frontend/screens/Onboarding/index.tsx
  src/frontend/screens/Onboarding/welcome/index.module.scss
  src/frontend/screens/Onboarding/welcome/index.tsx
Labels: PR: Ready-For-Test

#1168 feat(quest-page): add auto expand and tab filters
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.module.scss
  src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
  src/frontend/screens/Quests/index.module.scss
  src/frontend/screens/Quests/index.tsx
Labels: PR: Ready-For-Test

#1171 Analitycs consent modal update
  public/locales/en/translation.json
  src/frontend/App.tsx
  src/frontend/assets/hyperplay/check-circle.svg
  src/frontend/assets/hyperplay/consent-modal/check-circle.svg
  src/frontend/assets/hyperplay/consent-modal/x-close.svg
  src/frontend/assets/hyperplay/x-close.svg
  src/frontend/screens/Onboarding/analytics/CardPrivacyPolicy/index.module.scss
  src/frontend/screens/Onboarding/analytics/CardPrivacyPolicy/index.tsx
  src/frontend/screens/Onboarding/analytics/index.module.scss
  src/frontend/screens/Onboarding/analytics/index.tsx
Labels: PR: Ready-For-Test

#1175 [FIX] Steam on macOS not launching
  public/locales/en/translation.json
  src/backend/tools.ts
  src/frontend/screens/Library/components/SteamInstall/SteamInstallDialog.tsx
Labels: PR: Ready-For-Test

#1176 [UI] Refactor GamesSettings component to Tabs instead of Collapsible
  src/frontend/screens/Settings/components/SettingsModal/index.tsx
  src/frontend/screens/Settings/index.tsx
  src/frontend/screens/Settings/sections/GamesSettings/index.scss
  src/frontend/screens/Settings/sections/GamesSettings/index.tsx
Labels: PR: Ready-For-Test

#1156 [Fix] Native sideload failing because of relative path handler
  src/backend/__tests__/utils.test.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  src/backend/utils.ts
Labels: PR: Ready-For-Test

#1187 [UI] renamed public alpha to a dynamic version number on the Store
  public/locales/en/translation.json
  src/frontend/components/UI/AppVersion/index.tsx
  src/frontend/components/UI/TopNavBar/index.module.scss
  src/frontend/components/UI/TopNavBar/index.tsx
  src/frontend/screens/Settings/sections/GeneralSettings/index.tsx
Labels: PR: Ready-For-Test

#1164 [Fix] Portfolio main window buy/sell
  package.json
  src/backend/__mocks__/electron.ts
  src/backend/storeManagers/storeManagerCommon/games.ts
  yarn.lock
Labels: PR: Ready-For-Test

#1186 [Fix] Dialog fixed position breaking the view
  src/frontend/components/UI/Dialog/index.css
  src/frontend/components/UI/DialogHandler/components/MessageBoxModal/index.tsx
  src/frontend/components/UI/DialogHandler/index.tsx
  src/frontend/helpers/library.ts
  src/frontend/types.ts
Labels: PR: Ready-For-Review

#1181 [tech] Propagate full patching error message for download error events
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: Ready-For-Review, Type: Tech

#1191 [Metrics] Send version_from and version_to on Game Update Success event
  package.json
  src/backend/downloadmanager/utils.ts
  src/backend/metrics/types.ts
Labels: PR: Ready-For-Review

#1183 [Feat] Filter out ineligible completed quests
  .npmrc
  .yarnrc
  .yarnrc.yml
  package.json
  pnpm-lock.yaml
  src/backend/ipcHandlers/quests.ts
  src/frontend/components/UI/QuestDetails/index.tsx
  src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.tsx
  src/frontend/components/UI/QuestsViewer/index.tsx
  src/frontend/hooks/useGetQuestStates.ts
  src/frontend/hooks/useGetQuests.ts
Labels: PR: Ready-For-Test

#1185 [Fix] add wagmi patch to fallback to config.connectors
  package.json
  pnpm-lock.yaml
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#1193 [Fix] MetaMask stuck loading
  .github/workflows/build.yml
  package.json
  pnpm-lock.yaml
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#1195 [Fix] Token gated games install/update
  src/backend/api/library.ts
  src/backend/main.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/helpers/library.ts
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/ModDialog/index.tsx
Labels: PR: Ready-For-Review, PR: Ready-For-Test
