Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2025-01, with the labels that each got.

#1201 UI]replace twitter icon with x icon
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.css
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/frontend/components/UI/Sidebar/index.scss
Labels: PR: Ready-For-Test

#1200 [UI]fix search bar sizing on Quest page
  public/locales/en/translation.json
  src/frontend/screens/Quests/index.module.scss
  src/frontend/screens/Quests/index.tsx
Labels: PR: Ready-For-Test

#1202 [Fix] Update sidebar link from "Wiki" to "Docs"
  public/locales/en/translation.json
  src/frontend/App.tsx
  src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
  src/frontend/constants.ts
  src/frontend/screens/WebView/index.tsx
Labels: PR: Ready-For-Test

#1205 [TECH] Bump @hyperplay/patcher to version 0.0.21
  package.json
  pnpm-lock.yaml
Labels: PR: Ready-For-Test

#1169 [TECH] Add more logs and error handling for MW Mod support
  jest.config.js
  jest.setup.ts
  package.json
  pnpm-lock.yaml
  src/backend/__tests__/utils.test.ts
  src/backend/ipcHandlers/mods.ts
  src/backend/storeManagers/hyperplay/games.ts
  src/backend/utils.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#1213 [Fix] MetaMask extension notification window sometimes not showing in overlay
  package.json
  src/frontend/ExtensionManager/components/ExtensionContents/index.tsx
  src/frontend/screens/MetaMaskHome/index.tsx
  src/frontend/screens/MetaMaskPortfolio/index.tsx
Labels: PR: Ready-For-Test

#1218 [CI] Improve macOS build workflows
  .github/workflows/build-mac-x64.yml
  .github/workflows/build.yml
  .github/workflows/release_macOS.yml
Labels: PR: Ready-For-Review

#1219 feat(logger): add support for sending logs to sentry
  package.json
  pnpm-lock.yaml
  src/backend/api/misc.ts
  src/backend/logger/logger.ts
  src/backend/main.ts
  src/common/typedefs/ipcBridge.d.ts
  src/common/types.ts
Labels: PR: Ready-For-Review

#1180 [TECH] Refactor package.json, electron builder and others
  .eslintignore
  .eslintrc.json
  .github/workflows/build-mac-x64.yml
  .github/workflows/build.yml
  .github/workflows/flatpak-build.yml
  .github/workflows/release_macOS.yml
  electron-builder.yml
  package.json
  patches/app-builder-lib+24.13.3.patch
  pnpm-lock.yaml
Labels: PR: Ready-For-Test

#1194 [Fix] Clear cache and storage data on new browser game window
  src/backend/storeManagers/storeManagerCommon/games.ts
Labels: PR: Ready-For-Test

#1212 [Fix] MetaMask stuck loading after app update
  package.json
  pnpm-lock.yaml
  public/extensions/MetaMask_v10.22.2/background-3.js
  public/extensions/MetaMask_v10.22.2/common-0.js
  public/extensions/MetaMask_v10.22.2/manifest.json
  public/extensions/MetaMask_v10.22.2/scripts/app-init.js
  public/extensions/MetaMask_v10.22.2/scripts/inpage.js
  public/extensions/MetaMask_v10.22.2/scripts/sentry-install.js
  public/extensions/MetaMask_v10.22.2/ui-12.js
  src/backend/main.ts
Labels: PR: Ready-For-Test

#1221 chore: update quest-ui and chains packages
  package.json
  pnpm-lock.yaml
Labels: PR: Ready-For-Review, PR: Ready-For-Test
