Repository HyperPlay-Gaming/hyperplay-desktop-client, pull requests merged in 2025-04, with the labels that each got.

#1257 [Fix] rm process.noAsar changes
  src/backend/downloadmanager/utils.ts
  src/backend/services/ExtractZipService.ts
  src/backend/services/__tests__/ExtractZipService.test.ts
  src/backend/storeManagers/hyperplay/games.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test

#1203 feat: add active wallet integration
  package.json
  pnpm-lock.yaml
  public/locales/en/translation.json
  src/backend/api/questsAchievements.ts
  src/backend/ipcHandlers/quests.ts
  src/common/typedefs/ipcBridge.d.ts
  src/frontend/components/UI/QuestDetails/index.tsx
Labels: PR: Ready-For-Review

#1261 [FIX] Reload app due to extension only on app update
  src/backend/main.ts
  src/common/types/electron_store.ts
Labels: PR: Ready-For-Test

#1259 [FIx] Edge case where downloaded size is bigger than download size
  src/frontend/components/UI/DownloadToastManager/index.tsx
Labels: Priority: 3 - Medium, Severity: 2 - Medium

#1267 [UI] Add Alert for games with Third-Party Launchers
  package.json
  pnpm-lock.yaml
  public/locales/en/gamepage.json
  src/backend/storeManagers/hyperplay/utils.ts
  src/common/types.ts
  src/frontend/components/UI/AccessCodeContainer/index.tsx
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.module.scss
  src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
  src/frontend/screens/Library/components/InstallModal/SideloadDialog/Warning/index.tsx
Labels: PR: Ready-For-Test

#1271 [UI] Add Wallet Icons stack to WalletConnect on Wallet onboarding
  package.json
  pnpm-lock.yaml
  public/locales/en/translation.json
  src/frontend/assets/hyperplay/WalletConnect.svg
  src/frontend/assets/hyperplay/index.tsx
  src/frontend/screens/Onboarding/components/walletOption/index.tsx
  src/frontend/screens/Onboarding/index.module.scss
  src/frontend/screens/Onboarding/walletSelection/WalletConnectIconsStack.tsx
  src/frontend/screens/Onboarding/walletSelection/index.module.scss
  src/frontend/screens/Onboarding/walletSelection/index.tsx
Labels: PR: Ready-For-Review

#1274 [Fix] Auto-update
  package.json
  src/backend/main.ts
Labels: PR: Ready-For-Review, PR: Ready-For-Test, Change Failed

#1276 [Fix] pass search param to redirect correctly
  src/frontend/screens/Quests/index.tsx
Labels: PR: Ready-For-Review

#1278 [Chore] update proxy server
  package.json
  pnpm-lock.yaml
Labels: PR: Ready-For-Review

#1277 [Tech] Improve MetaMask Mobile connection
  package.json
  pnpm-lock.yaml
  src/backend/proxy/ipcHandlers.ts
Labels: PR: Ready-For-Review

#1279 [FIX] Overlay Overflow on small resolutions or high scales
  src/frontend/components/UI/QuestsViewer/index.module.scss
Labels: PR: Ready-For-Test

#1272 [Chore] Remove Error updater dialog
  public/locales/en/translation.json
  src/backend/updater/updater.ts
Labels: PR: Ready-For-Test
